trigger:
  branches:
    include:
    - main
  paths:
    include:
    - src/backend/**
    exclude:
    - src/frontend/**

pool:
  name: 'Training'

variables:
  IMAGE_TAG: 'v1.$(Build.BuildId)-$(Build.BuildDate)'  # Use Build.BuildDate for date format
  ACR_NAME: 'msabackend1'  # Replace with your Azure Container Registry name

steps:
# Use Node.js 16
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Use Node.js 16'

# Set the current date as custom variable to build tag using PowerShell
- script: |
    $date = Get-Date -Format "yyyyMMdd-HHmmss"  # Định dạng ngày, tháng, giờ, phút, giây
    Write-Host "##vso[task.setvariable variable=BuildDate]$date"
  displayName: 'Set Build Date with Time'

# Install and build the backend
- script: |
    cd src/backend
    npm install
  displayName: 'Install and build backend'

# Log in to Azure Container Registry (ACR)
- task: Docker@2
  inputs:
    command: 'login'
    containerRegistry: 'msabackend1-connection'  # Replace with your ACR Service Connection name
  displayName: 'Login to ACR'

# Build Docker image
- script: |
    docker build -t $(ACR_NAME).azurecr.io/backend:$(IMAGE_TAG) -f $(Build.SourcesDirectory)/src/backend/Dockerfile .
  displayName: 'Build Docker image'

# Push Docker image to ACR
- script: |
    docker push $(ACR_NAME).azurecr.io/backend:$(IMAGE_TAG)
  displayName: 'Push Docker image to ACR'
