trigger:
  branches:
    include:
    - main
  paths:
    include:
    - src/backend/**
    exclude:
    - src/frontend/**

pool:
  name: 'Training'

variables:
  IMAGE_TAG: 'v1.$(Build.BuildId)'
  ACR_NAME: 'msabackend1'  # Replace with your Azure Container Registry name
  GITOPS_REPO_URL: 'https://github.com/nashtech-tuannguyenhuu1/SD4994_msa_gitops.git'  # URL của repo SD4994_msa_gitops
  GITOPS_REPO_PATH: '$(Build.SourcesDirectory)/SD4994_msa_gitops'  # Đường dẫn nơi clone repo

steps:

# Kiểm tra các thư mục trong Build.SourcesDirectory
- script: |
    echo "Listing all folders in $(Build.SourcesDirectory)"
    dir $(Build.SourcesDirectory) /ad /b  # Windows
  displayName: 'List all folders in $(Build.SourcesDirectory)'

# Use Node.js 16
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Use Node.js 16'

# Install and build the backend
- script: |
    cd src/backend
    npm install
  displayName: 'Install and build backend'

# Log in to Azure Container Registry (ACR)
- task: Docker@2
  inputs:
    command: 'login'
    containerRegistry: 'msabackend1-connection'  # Replace with your ACR Service Connection name
  displayName: 'Login to ACR'

# Build Docker image
- script: |
    docker build -t $(ACR_NAME).azurecr.io/backend:$(IMAGE_TAG) -f $(Build.SourcesDirectory)/src/backend/Dockerfile $(Build.SourcesDirectory)/src/backend
  displayName: 'Build Docker image'

# Push Docker image to ACR
- script: |
    docker push $(ACR_NAME).azurecr.io/backend:$(IMAGE_TAG)
  displayName: 'Push Docker image to ACR'

# Clone repo SD4994_msa_gitops
- script: |
    git clone $(GITOPS_REPO_URL) $(GITOPS_REPO_PATH)  # Clone repo phụ vào thư mục chỉ định
    cd $(GITOPS_REPO_PATH)
    git status  # Kiểm tra trạng thái Git repo
  displayName: 'Clone SD4994_msa_gitops repository'

# Replace image in deployment.yaml file using PowerShell
- script: |
    echo "Listing all folders in $(Build.SourcesDirectory)/SD4994_msa_gitops"
    dir $(Build.SourcesDirectory) /ad /b  # Windows command to list directories
  displayName: 'List all folders in SD4994_msa_gitops'

# Replace image in deployment.yaml file using PowerShell
- script: |
    echo "Listing all folders in $(Build.SourcesDirectory)/SD4994_msa_gitops"
    dir $(Build.SourcesDirectory)/SD4994_msa_gitops /ad /b  # Windows command to list directories
  displayName: 'List all folders in SD4994_msa_gitops'

# Replace image in deployment.yaml file using PowerShell
- script: |
    echo "Replacing image tag in deployment.yaml"
    powershell -Command "(Get-Content $(GITOPS_REPO_PATH)/prod/backend/deployment.yaml) -replace 'image: .+', 'image: $(ACR_NAME).azurecr.io/backend:$(IMAGE_TAG)' | Set-Content $(GITOPS_REPO_PATH)/prod/backend/deployment.yaml"
  displayName: 'Update image tag in deployment.yaml'

# Commit và push thay đổi vào repo SD4994_msa_gitops
- script: |
    cd $(GITOPS_REPO_PATH)
    git config user.email "your-email@example.com"
    git config user.name "Your Name"
    git add prod/backend/deployment.yaml
    git commit -m "Update image tag in deployment.yaml to $(ACR_NAME).azurecr.io/backend:$(IMAGE_TAG)"
    git push origin main  # Đẩy thay đổi lên nhánh chính của repo SD4994_msa_gitops
  displayName: 'Commit and push changes to SD4994_msa_gitops repo'
