trigger:
  branches:
    include:
    - main
  paths:
    include:
    - src/frontend/**
    exclude:
    - src/backend/**

pool:
  name: 'Training'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Use Node.js 16'

- script: |
    cd frontend
    npm install
    npm run build
  displayName: 'Install and build frontend'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'frontend/build'
    ArtifactName: 'frontend-drop'
  displayName: 'Publish frontend artifacts'
