apiVersion: apps/v1
kind: Deployment
metadata:
  name: msa-mongodb-deployment
  labels:
    app: msa-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msa-mongodb
  template:
    metadata:
      labels:
        app: msa-mongodb
    spec:
      containers:
      - name: msa-mongodb
        image: mongo:5.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: example
